version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATANEWTON_API_KEY=${DATANEWTON_API_KEY}
      - API_FNS_API_KEY=${API_FNS_API_KEY}
      - DADATA_API_KEY=${DADATA_API_KEY}
      - OWNER_RESET_KEY=${OWNER_RESET_KEY}
      - 1USERLOGIN=${1USERLOGIN}
      - 1USERPASSWORD=${1USERPASSWORD}
      - 2USERLOGIN=${2USERLOGIN}
      - 2USERPASSWORD=${2USERPASSWORD}
    volumes:
      - ./instance:/app/instance
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
